Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DouriaPerfume.Controllers
{
    public class AboutController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

Controllers/PerfumeController.cs
using Douriaperfume.Data.Models;
using DouriaPerfume.Data.Interfaces;
using DouriaPerfume.Data.Interfaces;
using DouriaPerfume.Data.Models;
using DouriaPerfume.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DouriaPerfume.Controllers
{
    public class PerfumeController : Controller
    {
        private readonly IPerfumeRepository _perfumeRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PerfumeController(IPerfumeRepository PerfumeRepository, ICategoryRepository categoryRepository)
        {
            _perfumeRepository = PerfumeRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Perfume> Perfumes;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                Perfumes = _perfumeRepository.Perfumes.OrderBy(p => p.PerfumeId);
                currentCategory = "All Perfumes";
            }
            else
            {
                if (string.Equals("Men", _category, StringComparison.OrdinalIgnoreCase))
                    Perfumes = _perfumeRepository.Perfumes.Where(p => p.Category.CategoryName.Equals("Men")).OrderBy(p => p.Name);
                else
                    Perfumes = _perfumeRepository.Perfumes.Where(p => p.Category.CategoryName.Equals("Women")).OrderBy(p => p.Name);

                currentCategory = _category;
            }

            return View(new PerfumesListViewModel
            {
                Perfumes = Perfumes,
                CurrentCategory = currentCategory
            });
        }

        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Perfume> Perfumes;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                Perfumes = _perfumeRepository.Perfumes.OrderBy(p => p.PerfumeId);
            }
            else
            {
                Perfumes = _perfumeRepository.Perfumes.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Perfume/List.cshtml", new PerfumesListViewModel { Perfumes = Perfumes, CurrentCategory = "All Perfumes" });
        }

        public ViewResult Details(int PerfumeId)
        {
            var Perfume = _perfumeRepository.Perfumes.FirstOrDefault(d => d.PerfumeId == PerfumeId);
            if (Perfume == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(Perfume);
        }
    }
}

Controllers/ShoppingCartController.cs
using DouriaPerfume.Data.Models;
using DouriaPerfume.ViewModels;
using DouriaPerfume.Data.Interfaces;
using DouriaPerfume.Data.Models;
using DouriaPerfume.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DouriaPerfume.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPerfumeRepository _PerfumeRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IPerfumeRepository PerfumeRepository, ShoppingCart shoppingCart)
        {
            _PerfumeRepository = PerfumeRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        [Authorize]
        public RedirectToActionResult AddToShoppingCart(int PerfumeId)
        {
            var selectedPerfume = _PerfumeRepository.Perfumes.FirstOrDefault(p => p.PerfumeId == PerfumeId);
            if (selectedPerfume != null)
            {
                _shoppingCart.AddToCart(selectedPerfume, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int PerfumeId)
        {
            var selectedPerfume = _PerfumeRepository.Perfumes.FirstOrDefault(p => p.PerfumeId == PerfumeId);
            if (selectedPerfume != null)
            {
                _shoppingCart.RemoveFromCart(selectedPerfume);
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/Carousel.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

Views/Shared/PerfumSummary.cshtml
@model Perfume

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Perfume" asp-action="Details" asp-route-PerfumeId="@Model.PerfumeId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-PerfumeId="@Model.PerfumeId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

Views/Shared/PerfumeOverViewSummary.cshtml
@model Perfume

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Perfume" asp-action="Details" asp-route-id="@Model.PerfumeId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success " id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-pieId="@Model.PerfumeId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <title>DouriaPerfume</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">DouriaPerfume</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="About" asp-action="Index">About</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                @await Html.PartialAsync("LoginPartial")
                <form class="navbar-form navbar-right" asp-controller="Perfume" asp-action="Search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search for a Perfume" name="searchString" value="@ViewData["searchString"]">
                    </div>
                </form>
            </div>
        </div>
    </nav>
    <div class="container body-content" style="padding:50px;">
        @RenderBody()
        <hr />
        <footer>
            <p><a target="_blank" href="">&copy; 2024 - ISSAZAKOU Halima</a></p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>