Controllers/OrderController.cs
using DouriaPerfume.Data.Models;
using DouriaPerfume.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace DouriaPerfume.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some Perfumes first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order! :) ";
            return View();
        }
    }
}

Controllers/PerfumeController.cs
using Douriaperfume.Data.Models;
using DouriaPerfume.Data.Interfaces;
using DouriaPerfume.Data.Interfaces;
using DouriaPerfume.Data.Models;
using DouriaPerfume.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DouriaPerfume.Controllers
{
    public class PerfumeController : Controller
    {
        private readonly IPerfumeRepository _perfumeRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PerfumeController(IPerfumeRepository PerfumeRepository, ICategoryRepository categoryRepository)
        {
            _perfumeRepository = PerfumeRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Perfume> Perfumes;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                Perfumes = _perfumeRepository.Perfumes.OrderBy(p => p.PerfumeId);
                currentCategory = "All Perfumes";
            }
            else
            {
                if (string.Equals("Men", _category, StringComparison.OrdinalIgnoreCase))
                    Perfumes = _perfumeRepository.Perfumes.Where(p => p.Category.CategoryName.Equals("Men")).OrderBy(p => p.Name);
                else
                    Perfumes = _perfumeRepository.Perfumes.Where(p => p.Category.CategoryName.Equals("Women")).OrderBy(p => p.Name);

                currentCategory = _category;
            }

            return View(new PerfumesListViewModel
            {
                Perfumes = Perfumes,
                CurrentCategory = currentCategory
            });
        }

        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Perfume> Perfumes;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                Perfumes = _perfumeRepository.Perfumes.OrderBy(p => p.PerfumeId);
            }
            else
            {
                Perfumes = _perfumeRepository.Perfumes.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Perfume/List.cshtml", new PerfumesListViewModel { Perfumes = Perfumes, CurrentCategory = "All Perfumes" });
        }

        public ViewResult Details(int PerfumeId)
        {
            var Perfume = _perfumeRepository.Perfumes.FirstOrDefault(d => d.PerfumeId == PerfumeId);
            if (Perfume == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(Perfume);
        }
    }
}

Controllers/ShoppingCartController.cs
using DouriaPerfume.Data.Models;
using DouriaPerfume.ViewModels;
using DouriaPerfume.Data.Interfaces;
using DouriaPerfume.Data.Models;
using DouriaPerfume.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DouriaPerfume.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPerfumeRepository _PerfumeRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IPerfumeRepository PerfumeRepository, ShoppingCart shoppingCart)
        {
            _PerfumeRepository = PerfumeRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        [Authorize]
        public RedirectToActionResult AddToShoppingCart(int PerfumeId)
        {
            var selectedPerfume = _PerfumeRepository.Perfumes.FirstOrDefault(p => p.PerfumeId == PerfumeId);
            if (selectedPerfume != null)
            {
                _shoppingCart.AddToCart(selectedPerfume, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int PerfumeId)
        {
            var selectedPerfume = _PerfumeRepository.Perfumes.FirstOrDefault(p => p.PerfumeId == PerfumeId);
            if (selectedPerfume != null)
            {
                _shoppingCart.RemoveFromCart(selectedPerfume);
            }
            return RedirectToAction("Index");
        }

    }
}

Views/ShoppingCart.cshtml/Index.cshtml
@model ShoppingCartViewModel

<div class="row checkoutForm">
    <h2>Your shopping cart</h2>
    <h4>Here are the Perfumes in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Perfum</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Perfume.Name</td>
                    <td class="text-right">@line.Perfume.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Perfume.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-PerfumeId="@line.Perfume.PerfumeId"></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more Perfumes<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Perfume" asp-action="List" asp-route-category="Men">Men</a></li>
                    <li><a asp-controller="Perfume" asp-action="List" asp-route-category="Women">Women</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>